<?php

class OILM_Settings {

	public function register_settings() {
		register_setting( 'oilm_settings_group', 'oilm_settings', array( $this, 'sanitize_settings' ) );

		// General Tab
		add_settings_section( 'oilm_general_settings', __( 'General Settings', 'op-internal-link-manager' ), array( $this, 'general_settings_cb' ), 'oilm_settings_general' );
		add_settings_field( 'enable_plugin', __( 'Enable Plugin', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_general', 'oilm_general_settings', array( 'id' => 'enable_plugin' ) );
		add_settings_field( 'global_max_links', __( 'Global Max Links per Page', 'op-internal-link-manager' ), array( $this, 'render_number' ), 'oilm_settings_general', 'oilm_general_settings', array( 'id' => 'global_max_links', 'desc' => '0 for unlimited' ) );
		add_settings_field( 'global_max_url_links', __( 'Global Max Links per Target URL per Page', 'op-internal-link-manager' ), array( $this, 'render_number' ), 'oilm_settings_general', 'oilm_general_settings', array( 'id' => 'global_max_url_links', 'desc' => 'Minimum 1. Prevents duplicate links to the same URL on a single page.' ) );
		add_settings_field( 'link_css_class', __( 'Generated Link CSS Class', 'op-internal-link-manager' ), array( $this, 'render_text' ), 'oilm_settings_general', 'oilm_general_settings', array( 'id' => 'link_css_class', 'default' => 'op-internal-link', 'desc' => 'CSS class added to links generated by this plugin. Separate multiple classes with spaces.' ) );
		add_settings_field( 'default_new_tab', __( 'Open links in new tab default', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_general', 'oilm_general_settings', array( 'id' => 'default_new_tab' ) );
		add_settings_field( 'default_nofollow', __( 'Add nofollow default', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_general', 'oilm_general_settings', array( 'id' => 'default_nofollow' ) );
		add_settings_field( 'global_override_rule_attributes', __( 'Override Rule Link Attributes', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_general', 'oilm_general_settings', array( 'id' => 'global_override_rule_attributes', 'desc' => 'Use the global new tab and nofollow settings instead of each rule\'s values.' ) );

		// Targeting Tab
		add_settings_section( 'oilm_targeting_settings', __( 'Content Targeting', 'op-internal-link-manager' ), array( $this, 'targeting_settings_cb' ), 'oilm_settings_targeting' );
		add_settings_field( 'enabled_post_types', __( 'Enabled Post Types', 'op-internal-link-manager' ), array( $this, 'render_post_types' ), 'oilm_settings_targeting', 'oilm_targeting_settings' );
		add_settings_field( 'process_excerpts', __( 'Process Excerpts', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_targeting', 'oilm_targeting_settings', array( 'id' => 'process_excerpts', 'desc' => 'Add links inside post excerpts.' ) );
		add_settings_field( 'process_comments', __( 'Process Comments', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_targeting', 'oilm_targeting_settings', array( 'id' => 'process_comments', 'desc' => 'Add links inside user comments.' ) );
		add_settings_field( 'enable_elementor', __( 'Enable Elementor Compatibility', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_targeting', 'oilm_targeting_settings', array( 'id' => 'enable_elementor' ) );

		// Exclusions Tab
		add_settings_section( 'oilm_exclusions_settings', __( 'Exclusions', 'op-internal-link-manager' ), array( $this, 'exclusions_settings_cb' ), 'oilm_settings_exclusions' );
		add_settings_field( 'exclude_post_ids', __( 'Exclude Post/Page IDs', 'op-internal-link-manager' ), array( $this, 'render_text' ), 'oilm_settings_exclusions', 'oilm_exclusions_settings', array( 'id' => 'exclude_post_ids', 'desc' => 'Comma-separated list of Post IDs to never process.' ) );
		add_settings_field( 'exclude_headings', __( 'Exclude Headings', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_exclusions', 'oilm_exclusions_settings', array( 'id' => 'exclude_headings', 'desc' => 'Do not add links inside H1-H6 tags.' ) );
		add_settings_field( 'exclude_existing_links', __( 'Exclude Existing Links', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_exclusions', 'oilm_exclusions_settings', array( 'id' => 'exclude_existing_links', 'desc' => 'Do not add links inside existing anchor tags.' ) );
		add_settings_field( 'exclude_elements', __( 'Exclude Specific HTML Elements', 'op-internal-link-manager' ), array( $this, 'render_exclude_elements' ), 'oilm_settings_exclusions', 'oilm_exclusions_settings' );

		// Advanced Tab
		add_settings_section( 'oilm_advanced_settings', __( 'Advanced Configuration', 'op-internal-link-manager' ), array( $this, 'advanced_settings_cb' ), 'oilm_settings_advanced' );
		add_settings_field( 'enable_pluralization', __( 'Enable Pluralization', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_advanced', 'oilm_advanced_settings', array( 'id' => 'enable_pluralization', 'desc' => 'Automatically match basic plural forms (e.g., adding "s" or "es") of keywords.' ) );
		add_settings_field( 'first_occurrence_only', __( 'First Occurrence Only', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_advanced', 'oilm_advanced_settings', array( 'id' => 'first_occurrence_only', 'desc' => 'Only link the very first matched keyword on the entire page, then stop processing.' ) );
		add_settings_field( 'debug_mode', __( 'Debug Mode', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_advanced', 'oilm_advanced_settings', array( 'id' => 'debug_mode' ) );
		add_settings_field( 'remove_data_on_uninstall', __( 'Remove Data on Uninstall', 'op-internal-link-manager' ), array( $this, 'render_checkbox' ), 'oilm_settings_advanced', 'oilm_advanced_settings', array( 'id' => 'remove_data_on_uninstall', 'desc' => 'Delete all rules and settings if the plugin is uninstalled.' ) );
	}

	public function sanitize_settings( $input ) {
		if ( ! is_array( $input ) ) {
			$input = array();
		}

		$active_tab = isset( $_POST['oilm_active_tab'] ) ? sanitize_key( wp_unslash( $_POST['oilm_active_tab'] ) ) : 'general';
		$settings = wp_parse_args( get_option( 'oilm_settings', array() ), $this->get_default_settings() );
		$tab_fields = $this->get_tab_fields();

		if ( isset( $tab_fields[ $active_tab ] ) ) {
			foreach ( $tab_fields[ $active_tab ] as $field ) {
				if ( in_array( $field, $this->get_checkbox_fields(), true ) ) {
					$settings[ $field ] = 0;
				}

				if ( in_array( $field, array( 'enabled_post_types', 'exclude_elements' ), true ) ) {
					$settings[ $field ] = array();
				}
			}
		}

		foreach ( $input as $key => $value ) {
			switch ( $key ) {
				case 'global_max_links':
				case 'global_max_url_links':
					$settings[ $key ] = absint( $value );
					break;

				case 'enable_plugin':
				case 'default_new_tab':
				case 'default_nofollow':
				case 'global_override_rule_attributes':
				case 'process_excerpts':
				case 'process_comments':
				case 'enable_elementor':
				case 'exclude_headings':
				case 'exclude_existing_links':
				case 'enable_pluralization':
				case 'first_occurrence_only':
				case 'debug_mode':
				case 'remove_data_on_uninstall':
					$settings[ $key ] = $value ? 1 : 0;
					break;

				case 'link_css_class':
					$classes = preg_split( '/\s+/', trim( wp_unslash( $value ) ) );
					$classes = array_filter( array_map( 'sanitize_html_class', $classes ) );
					$settings[ $key ] = implode( ' ', $classes );
					break;

				case 'enabled_post_types':
				case 'exclude_elements':
					$settings[ $key ] = is_array( $value ) ? array_map( 'sanitize_key', wp_unslash( $value ) ) : array();
					break;

				case 'exclude_post_ids':
					$settings[ $key ] = sanitize_text_field( wp_unslash( $value ) );
					break;
			}
		}

		if ( '' === $settings['link_css_class'] ) {
			$settings['link_css_class'] = 'op-internal-link';
		}

		return $settings;
	}

	private function get_default_settings() {
		return array(
			'global_max_links' => 0,
			'global_max_url_links' => 1,
			'link_css_class' => 'op-internal-link',
			'enable_plugin' => 1,
			'enabled_post_types' => array( 'post', 'page' ),
			'enable_elementor' => 1,
			'exclude_headings' => 1,
			'exclude_existing_links' => 1,
			'default_new_tab' => 0,
			'default_nofollow' => 0,
			'global_override_rule_attributes' => 0,
			'debug_mode' => 0,
			'remove_data_on_uninstall' => 0,
			'process_excerpts' => 0,
			'process_comments' => 0,
			'exclude_post_ids' => '',
			'exclude_elements' => array(),
			'enable_pluralization' => 0,
			'first_occurrence_only' => 0,
		);
	}

	private function get_tab_fields() {
		return array(
			'general' => array( 'enable_plugin', 'global_max_links', 'global_max_url_links', 'link_css_class', 'default_new_tab', 'default_nofollow', 'global_override_rule_attributes' ),
			'targeting' => array( 'enabled_post_types', 'process_excerpts', 'process_comments', 'enable_elementor' ),
			'exclusions' => array( 'exclude_post_ids', 'exclude_headings', 'exclude_existing_links', 'exclude_elements' ),
			'advanced' => array( 'enable_pluralization', 'first_occurrence_only', 'debug_mode', 'remove_data_on_uninstall' ),
		);
	}

	private function get_checkbox_fields() {
		return array(
			'enable_plugin',
			'default_new_tab',
			'default_nofollow',
			'global_override_rule_attributes',
			'process_excerpts',
			'process_comments',
			'enable_elementor',
			'exclude_headings',
			'exclude_existing_links',
			'enable_pluralization',
			'first_occurrence_only',
			'debug_mode',
			'remove_data_on_uninstall',
		);
	}

	public function general_settings_cb() { echo '<p>' . __( 'Configure global defaults and limits.', 'op-internal-link-manager' ) . '</p>'; }
	public function targeting_settings_cb() { echo '<p>' . __( 'Configure where links should be inserted.', 'op-internal-link-manager' ) . '</p>'; }
	public function exclusions_settings_cb() { echo '<p>' . __( 'Configure where links should NOT be inserted.', 'op-internal-link-manager' ) . '</p>'; }
	public function advanced_settings_cb() { echo '<p>' . __( 'Advanced matching and system configurations.', 'op-internal-link-manager' ) . '</p>'; }

	public function render_checkbox( $args ) {
		$options = get_option( 'oilm_settings' );
		$id = $args['id'];
		$checked = isset( $options[$id] ) ? $options[$id] : 0;
		$desc = isset( $args['desc'] ) ? $args['desc'] : '';
		$label = $desc ? $desc : __( 'Enabled', 'op-internal-link-manager' );

		echo '<label class="oilm-switch-field">';
		echo '<input type="checkbox" class="oilm-switch-input" name="oilm_settings[' . esc_attr($id) . ']" value="1" ' . checked( 1, $checked, false ) . ' />';
		echo '<span class="oilm-switch" aria-hidden="true"></span>';
		echo '<span class="oilm-switch-label">' . esc_html( $label ) . '</span>';
		echo '</label>';
	}

	public function render_text( $args ) {
		$options = get_option( 'oilm_settings' );
		$id = $args['id'];
		$val = isset( $options[$id] ) ? $options[$id] : ( isset( $args['default'] ) ? $args['default'] : '' );
		echo '<input type="text" name="oilm_settings[' . esc_attr($id) . ']" value="' . esc_attr($val) . '" class="regular-text" />';
		if ( isset( $args['desc'] ) ) {
			echo '<p class="description">' . esc_html( $args['desc'] ) . '</p>';
		}
	}

	public function render_number( $args ) {
		$options = get_option( 'oilm_settings' );
		$id = $args['id'];
		$val = isset( $options[$id] ) ? absint($options[$id]) : 0;
		echo '<input type="number" name="oilm_settings[' . esc_attr($id) . ']" value="' . esc_attr($val) . '" min="0" />';
		if ( isset( $args['desc'] ) ) {
			echo '<p class="description">' . esc_html( $args['desc'] ) . '</p>';
		}
	}

	public function render_post_types() {
		$options = get_option( 'oilm_settings' );
		$enabled = isset( $options['enabled_post_types'] ) && is_array( $options['enabled_post_types'] ) ? $options['enabled_post_types'] : array('post', 'page');
		$post_types = get_post_types( array( 'public' => true ), 'objects' );
		
		echo '<select name="oilm_settings[enabled_post_types][]" multiple="multiple" class="oilm-select2 regular-text">';
		foreach ( $post_types as $pt ) {
			if ( $pt->name === 'attachment' ) continue;
			$selected = in_array( $pt->name, $enabled ) ? 'selected="selected"' : '';
			echo '<option value="' . esc_attr( $pt->name ) . '" ' . $selected . '>' . esc_html( $pt->label ) . '</option>';
		}
		echo '</select>';
	}

	public function render_exclude_elements() {
		$options = get_option( 'oilm_settings' );
		$excluded = isset( $options['exclude_elements'] ) && is_array( $options['exclude_elements'] ) ? $options['exclude_elements'] : array();
		
		$elements = array( 'blockquote', 'strong', 'em', 'i', 'b', 'ul', 'ol', 'li', 'table', 'span' );
		
		echo '<select name="oilm_settings[exclude_elements][]" multiple="multiple" class="oilm-select2 regular-text">';
		foreach ( $elements as $el ) {
			$selected = in_array( $el, $excluded ) ? 'selected="selected"' : '';
			echo '<option value="' . esc_attr( $el ) . '" ' . $selected . '>&lt;' . esc_html( $el ) . '&gt;</option>';
		}
		echo '</select>';
		echo '<p class="description">Select HTML elements where links should NEVER be inserted.</p>';
	}

	public function render_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$active_tab = isset( $_GET['tab'] ) ? sanitize_key( $_GET['tab'] ) : 'general';
		$tabs = array(
			'general'    => __( 'General', 'op-internal-link-manager' ),
			'targeting'  => __( 'Targeting', 'op-internal-link-manager' ),
			'exclusions' => __( 'Exclusions', 'op-internal-link-manager' ),
			'advanced'   => __( 'Advanced', 'op-internal-link-manager' ),
		);

		if ( ! isset( $tabs[ $active_tab ] ) ) {
			$active_tab = 'general';
		}
		?>
		<div class="wrap oilm-modern-wrap oilm-settings-page">
			<h1><?php echo esc_html( get_admin_page_title() ); ?></h1>
			
			<nav class="nav-tab-wrapper oilm-settings-tabs" aria-label="<?php esc_attr_e( 'Settings sections', 'op-internal-link-manager' ); ?>">
				<?php foreach ( $tabs as $tab => $label ) : ?>
					<a href="<?php echo esc_url( admin_url( 'admin.php?page=op-internal-link-manager-settings&tab=' . $tab ) ); ?>" class="nav-tab <?php echo $active_tab === $tab ? 'nav-tab-active' : ''; ?>" <?php echo $active_tab === $tab ? 'aria-current="page"' : ''; ?>>
						<?php echo esc_html( $label ); ?>
					</a>
				<?php endforeach; ?>
			</nav>

			<form action="options.php" method="post" class="oilm-settings-card">
				<?php
				settings_fields( 'oilm_settings_group' );
				echo '<input type="hidden" name="oilm_active_tab" value="' . esc_attr( $active_tab ) . '" />';
				do_settings_sections( 'oilm_settings_' . $active_tab );
				submit_button();
				?>
			</form>
		</div>
		<?php
	}
}
